### ISSUE TITLE
[WD]/res/admission_first_ids.npy created in 0_createAdmissionList.ipynb is incorrect!

### ISSUE THREAD

**Issue by fzhang1991** [USC-Melady/Benchmarking_DL_MIMICIII#12]
Based on MIMICIII-Demo dataset, for subject_id=40310, hadm_id=157609 is saved, while the first hadm_id is 186361 .

mimic=> select subject_id,hadm_id,admittime from admissions where subject_id=40310;
 subject_id | hadm_id |      admittime
------------+---------+---------------------
      40310 |  186361 | 2144-07-11 15:02:00
      40310 |  157609 | 2144-12-24 16:16:00
(2 rows)

**Comment by linzhenyuyuchen** [comment]
Hello, i have the same problem as yours.

In `0_createAdmissionList.ipynb` - `Remove non-first admissions` block, 
the author uses sql `cur.execute('select hadm_id from admission_ids where hadm_id in (select distinct on (subject_id) hadm_id from (select * from mimiciii.admissions order by admittime) tt)')` which gets random result (not first admission) from ADMISSIONS TABLE.  Ref. [PostgreSQL SELECT DISTINCT
](https://www.postgresqltutorial.com/postgresql-select-distinct/)

For example, in ADMISSION TABLE:
subject_id | hadm_id| admittime
-- | -- | --
13830 | 146964 | 2185/11/28 17:56
13830 | 137613 | 2187/10/9 13:08
13830 | 136134 | 2190/9/8 11:36
13830 | 114740 | 2192/2/5 5:36
13830 | 148667 | 2193/10/22 17:58

`146964` should be selected as first admission, but it is not in `res/admission_first_ids.npy` which is generated in `0_createAdmissionList.ipynb`.

---

When i changed the sql to `cur.execute('select hadm_id from admission_ids where hadm_id in (select distinct on (subject_id) hadm_id from mimiciii.admissions order by subject_id,admittime)')`, everything goes well with first admission.

---

I will appreciate very much if any reply or doubt on my ideas.

**Comment by mengcz13** [comment]
Hi @linzhenyuyuchen , thanks for pointing this out! Yeah, I think this is a bug and should be fixed. Have you tested its effect on results?

**Comment by linzhenyuyuchen** [comment]
@mengcz13 Hello, after extracting data from MIMIC-III, i found that mortality and icd-9 group propotation are different from yours which results in different AUROC and AUPRC.

---

|In-hospital|2-day|3-day|30-day|1-year|TOTAL|
| --- | --- | --- | --- | --- | --- |
|0.099|	0.016|	0.027|	0.138|	0.241|	35623|

---

**Comment by mengcz13** [comment]
@linzhenyuyuchen Hi, thanks for showing the difference! It seems that the proportion is still close to the numbers in the paper, could you show how different the AUROC and AUPRC are?
