### ISSUE TITLE
A lot of time to execute 1_getItemIdList.ipynb and 4_filterItemId_chart.ipynb ?

### ISSUE THREAD

**Issue by ElAbedHoussem** [USC-Melady/Benchmarking_DL_MIMICIII#6]
I'm trying to execute file named **1_getItemIdList.ipynb** and **4_filterItemId_chart.ipynb** from the Benchmarking project
https://github.com/USC-Melady/Benchmarking_DL_MIMICIII
My problem is, that this two scripts take a lot of time , I speek about days, and this is not normal.
For the file **4_filterItemId_chart.ipynb** I tried to print the sql queries and to make a counter to track the number of the current iteration. I found after 2 days of execution that he is in the iteration number 642 of 6443 itarations this is not normal.
What is the cause of thhis problem please

**Comment by mengcz13** [comment]
Hi,

How many CPU cores you used for running? 

The current implementation used multiple processes to execute SQL queries and that may cause speed problems when the number of available CPU cores is too small (e.g. on personal laptops).

A better practice should be using coroutines that are more light-weighted, but I am not sure if I can fix it in a short time. One possible quick fix is to try increasing the number of processes in the process Pool (by default the script uses 2x {number of cpu cores}).

Thanks!

**Comment by safynaz** [comment]
I have the same problem, when running these files (1_..., 4_...) , they take a lot of time and in the end not running.
when running file 4_filterItemId_chart.ipynb, i left my pc 24 hours and after that it sleep and every thing go :( and all this time consumed. 
please tell me how to solve this problem to run this file.
I'm using my personal PC, tell me what are the requirements to run this benchmark.

Thanks

**Comment by mengcz13** [comment]
> I have the same problem, when running these files (1_..., 4_...) , they take a lot of time and in the end not running.
> when running file 4_filterItemId_chart.ipynb, i left my pc 24 hours and after that it sleep and every thing go :( and all this time consumed.
> please tell me how to solve this problem to run this file.
> I'm using my personal PC, tell me what are the requirements to run this benchmark.
> 
> Thanks

Have you tried increasing the number of processes?

**Comment by mengcz13** [comment]
I have updated 1_getItemIdList.ipynb and 4_filterItemId_chart.ipynb. Now with 4 processes running by default, they should finish in around 1 hour.

You need to install `tqdm` to show the progress bars in these notebooks:
```
conda install tqdm
```
