### ISSUE TITLE
Error from numpy.savez in 11_get_time_series_sample_99plus-features-raw_48hrs.ipynb

### ISSUE THREAD

**Issue by JanmajaySingh** [USC-Melady/Benchmarking_DL_MIMICIII#7]
I get the following error;

`RuntimeError: File size unexpectedly exceeded ZIP64 limit`

when trying to save the **normed-ep.npz** file.
No such error is seen when saving the same file for 24hrs data.

Although this is related to an issue in numpy itself (#13153), I was wondering if it was not encountered in numpy 1.13.1 (stated in repository README)?

For reference I am using numpy 1.16.4 .

**Comment by PeterChe1990** [comment]
Yes, this is an internal issue in numpy. Please refer to #4 .
I'm not sure whether the numpy team has fixed it.

**Comment by JanmajaySingh** [comment]
Sorry, I had not checked the closed issues.
I solved the problem by individually saving the arrays with numpy.save and with different filenames. 
It's just a bit more difficult to retrieve. 
Thanks!
