### ISSUE TITLE
Go back from ICD9 y_pred prediction to the ICD9 Code using SuperLearner and Deep Learning 

### ISSUE THREAD

**Issue by ElAbedHoussem** [USC-Melady/Benchmarking_DL_MIMICIII#8]
Hello, I just run an d save all models, using SuperLearner and Deep Learning. Also, I test them using new input (in the case of SuperLearner for icd9, los and mor).
Now, in the first step, I am asking how to test Deep Learning models using new data, which is the input (example) of models.
My second question is, from the predicted value of ICD9 models(for Super Learner and Deep Learner) how to go back to the ICD9 code.

**Comment by mengcz13** [comment]
Hi, sorry for the late reply :(

1. I don't think I implemented the loading part for new data... But you can write your own data loader to transform your new data into the same format used in our DL models.

2. I don't think it's possible to recover some model's code from its prediction results. Can you clarify what you want to implement?
