### ISSUE TITLE
4_filterItemId_chart.ipynb not run????

### ISSUE THREAD

**Issue by safynaz** [USC-Melady/Benchmarking_DL_MIMICIII#9]
when running file 4_filterItemId_chart.ipynb, i left my pc 24 hours and after that it sleep and every thing go :( and all this time consumed.
It take a lot of time and finally my pc sleep and not run :( .
please tell me how to solve this problem to run this file.
I'm using my personal PC, tell me what are the requirements to run this benchmark.

Thanks

**Comment by XuZhao-design** [comment]
Hi, I am running file 2_filterItemId_input.ipynb. It also took me a lot of time and did not work. Did your PC work well with file 2_filterItemId_input.ipynb?

**Comment by mengcz13** [comment]
See #6
